- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    # - !type:RoleTimeRequirement # SpaceFactory
      # role: JobAtmosphericTechnician # SpaceFactory
      # time: 21600 #6 hrs # SpaceFactory
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom # SpaceFactory
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathAcidifierImplantSF ] # SpaceFactory
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  accessGroups:
  - AllAccess

- type: startingGear
  id: ChiefEngineerGear
  equipment:
#    head: ClothingHeadHatHardhatWhiteSF
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSF
    back: ClothingBackpackEngineeringFilledSF # ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesBootsMagAdvSF # ClothingShoesColorBrown
    outerClothing: ClothingOuterVestHazardSF # SpaceFactory
    id: CEPDASF
#    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCESF
#    belt: ClothingBeltUtilityEngineering
  innerClothingSkirt: ClothingUniformJumpskirtChiefEngineerSF
  satchel: ClothingBackpackEngineeringFilledSF # ClothingBackpackSatchelChiefEngineerFilled
  duffelbag: ClothingBackpackEngineeringFilledSF # ClothingBackpackDuffelChiefEngineerFilled
