- type: entity
  save: false
  id: BaseMobStrongPassiveRegen
  abstract: true
  components:
  - type: PassiveDamage # Slight passive regen. Assuming one damage type, comes out to about 4 damage a minute.
    allowedStates:
    - Alive
    damageCap: 400
    damage:
      groups:
        Brute: -3
        Burn: -3
        Airloss: -3
        Toxin: -7
        Genetic: -7
